ot:
  name: "watson"
  strategy: "trend_following"
  description: "トレンドフォロー戦略"

trading:
  max_position_size: 0.1 # 中程度のポジション
  risk_limit: 0.02 # バランス取れたリスク
  order_timeout: 30 # 通常の執行速度
  heartbeat_interval: 60 # 標準的な間隔
  max_daily_trades: 50 # 中頻度取引
  max_daily_loss: 200 # 中程度の損失許容
  min_profit_threshold: 0.005 # 0.5%以上で利確検討

risk_management:
  stop_loss_ratio: 0.02 # 2%で損切り
  take_profit_ratio: 0.05 # 5%で利確
  max_drawdown: 0.05 # 5%で全停止
  position_sizing: "percentage" # 資金の割合でサイジング

performance:
  execution_speed: "fast" # 高速
  latency_threshold: 10 # 10ms以上で警告
  tick_interval: 0.1 # 100msごとにチェック
