version: "3.8"

services:
  sherrinford:
    build:
      context: ..
      dockerfile: bots/sherrinford/Dockerfile
    env_file: ../env/sherrinford.env
    volumes:
      - sherrinford-data:/data
      - sherrinford-logs:/app/logs
    restart: unless-stopped

  sherrinford-redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: ../env/sherrinford.env
    volumes:
      - sherrinford-redis:/data

  watson:
    build:
      context: ..
      dockerfile: bots/watson/Dockerfile
    env_file: ../env/watson.env
    volumes:
      - watson-data:/data
      - watson-logs:/app/logs
    restart: unless-stopped
  watson-redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: ../env/watson.env
    volumes:
      - watson-redis:/data

volumes:
  sherrinford-data:
  sherrinford-logs:
  sherrinford-redis:
  watson-data:
  watson-logs:
  watson-redis:
