# Base configuration for all environments
app:
  name: "root-bot"
  version: "1.0.0"

logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

database:
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600

redis:
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5

trading:
  default_position_size: 0.1
  max_position_size: 1.0
  default_risk_limit: 0.01
  max_risk_limit: 0.05

monitoring:
  metrics_enabled: true
  health_check_interval: 30
  alert_threshold: 0.8
