# Production environment configuration
extends: base.yml

environment: production

logging:
  level: WARNING
  handlers:
    - file
    - syslog

database:
  pool_size: 20
  max_overflow: 30

redis:
  max_connections: 50

trading:
  paper_trading: false
  position_size: 1.0
  risk_limit: 0.02

monitoring:
  health_check_interval: 60
  alert_enabled: true
  metrics_retention: 30d

security:
  ssl_required: true
  api_key_rotation: true

api:
  rate_limit: 1000
  timeout: 10
