name: CI-CD
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install flake8 mypy pytest
      - run: flake8 bots shared
      - run: mypy bots shared
      - run: pytest -q topgun/tests/

  build-push:
    needs: test
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        bot: [sherrinford, watson, gmo_board_watcher]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: |
          docker build -f bots/${{ matrix.bot }}/Dockerfile \
            -t ghcr.io/${{ github.repository }}/${{ matrix.bot }}:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/${{ matrix.bot }}:${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd /srv/root-bot
            git pull
            docker-compose -f docker/docker-compose.prod.yml pull
            docker-compose -f docker/docker-compose.prod.yml up -d
